# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogNetwork(object):
    def setupUi(self, DialogNetwork):
        DialogNetwork.setObjectName("DialogNetwork")
        DialogNetwork.resize(318, 274)
        self.buttonBoxOkCancek = QtWidgets.QDialogButtonBox(DialogNetwork)
        self.buttonBoxOkCancek.setGeometry(QtCore.QRect(20, 230, 271, 32))
        self.buttonBoxOkCancek.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxOkCancek.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxOkCancek.setObjectName("buttonBoxOkCancek")
        self.labelLocalIp = QtWidgets.QLabel(DialogNetwork)
        self.labelLocalIp.setGeometry(QtCore.QRect(30, 30, 61, 21))
        self.labelLocalIp.setObjectName("labelLocalIp")
        self.labelLocalPort = QtWidgets.QLabel(DialogNetwork)
        self.labelLocalPort.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.labelLocalPort.setObjectName("labelLocalPort")
        self.labelSendIp = QtWidgets.QLabel(DialogNetwork)
        self.labelSendIp.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.labelSendIp.setObjectName("labelSendIp")
        self.labelSendPort = QtWidgets.QLabel(DialogNetwork)
        self.labelSendPort.setGeometry(QtCore.QRect(30, 150, 71, 21))
        self.labelSendPort.setObjectName("labelSendPort")
        self.lineEditLocaIp = QtWidgets.QLineEdit(DialogNetwork)
        self.lineEditLocaIp.setGeometry(QtCore.QRect(100, 30, 191, 20))
        self.lineEditLocaIp.setObjectName("lineEditLocaIp")
        self.lineEditLocalPort = QtWidgets.QLineEdit(DialogNetwork)
        self.lineEditLocalPort.setGeometry(QtCore.QRect(100, 70, 191, 20))
        self.lineEditLocalPort.setObjectName("lineEditLocalPort")
        self.lineEditSendIp = QtWidgets.QLineEdit(DialogNetwork)
        self.lineEditSendIp.setGeometry(QtCore.QRect(100, 110, 191, 20))
        self.lineEditSendIp.setObjectName("lineEditSendIp")
        self.lineEditSendPort = QtWidgets.QLineEdit(DialogNetwork)
        self.lineEditSendPort.setGeometry(QtCore.QRect(100, 150, 191, 20))
        self.lineEditSendPort.setObjectName("lineEditSendPort")
        self.pushButtonRetrieveIp = QtWidgets.QPushButton(DialogNetwork)
        self.pushButtonRetrieveIp.setGeometry(QtCore.QRect(140, 190, 151, 31))
        self.pushButtonRetrieveIp.setObjectName("pushButtonRetrieveIp")

        self.retranslateUi(DialogNetwork)
        self.buttonBoxOkCancek.accepted.connect(DialogNetwork.accept)
        self.buttonBoxOkCancek.rejected.connect(DialogNetwork.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNetwork)

    def retranslateUi(self, DialogNetwork):
        _translate = QtCore.QCoreApplication.translate
        DialogNetwork.setWindowTitle(_translate("DialogNetwork", "Network"))
        self.labelLocalIp.setText(_translate("DialogNetwork", "Local IP"))
        self.labelLocalPort.setText(_translate("DialogNetwork", "Local Port"))
        self.labelSendIp.setText(_translate("DialogNetwork", "Send IP"))
        self.labelSendPort.setText(_translate("DialogNetwork", "Send Port"))
        self.pushButtonRetrieveIp.setText(_translate("DialogNetwork", "Retrive IP"))

#程序入口，程序从此处启动PyQt设计的窗体
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    DialogNetwork = QtWidgets.QDialog()
    ui = Ui_DialogNetwork()
    ui.setupUi(DialogNetwork)
    DialogNetwork.show()
    sys.exit(app.exec_())