# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NncDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogNncSetting(object):
    def setupUi(self, DialogNncSetting):
        DialogNncSetting.setObjectName("DialogNncSetting")
        DialogNncSetting.resize(400, 300)
        self.buttonBoxOkCancel = QtWidgets.QDialogButtonBox(DialogNncSetting)
        self.buttonBoxOkCancel.setGeometry(QtCore.QRect(50, 240, 291, 32))
        self.buttonBoxOkCancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxOkCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxOkCancel.setObjectName("buttonBoxOkCancel")
        self.labelEnterHex = QtWidgets.QLabel(DialogNncSetting)
        self.labelEnterHex.setGeometry(QtCore.QRect(20, 30, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelEnterHex.setFont(font)
        self.labelEnterHex.setObjectName("labelEnterHex")
        self.lineEditAcctFrom = QtWidgets.QLineEdit(DialogNncSetting)
        self.lineEditAcctFrom.setGeometry(QtCore.QRect(140, 90, 201, 20))
        self.lineEditAcctFrom.setObjectName("lineEditAcctFrom")
        self.lineEditAcctTo = QtWidgets.QLineEdit(DialogNncSetting)
        self.lineEditAcctTo.setGeometry(QtCore.QRect(140, 140, 201, 20))
        self.lineEditAcctTo.setObjectName("lineEditAcctTo")
        self.lineEditStep = QtWidgets.QLineEdit(DialogNncSetting)
        self.lineEditStep.setGeometry(QtCore.QRect(140, 190, 201, 20))
        self.lineEditStep.setObjectName("lineEditStep")
        self.labelAcctFrom = QtWidgets.QLabel(DialogNncSetting)
        self.labelAcctFrom.setGeometry(QtCore.QRect(40, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAcctFrom.setFont(font)
        self.labelAcctFrom.setObjectName("labelAcctFrom")
        self.labelAcctTo = QtWidgets.QLabel(DialogNncSetting)
        self.labelAcctTo.setGeometry(QtCore.QRect(40, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAcctTo.setFont(font)
        self.labelAcctTo.setObjectName("labelAcctTo")
        self.labelStep = QtWidgets.QLabel(DialogNncSetting)
        self.labelStep.setGeometry(QtCore.QRect(40, 190, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStep.setFont(font)
        self.labelStep.setObjectName("labelStep")

        self.retranslateUi(DialogNncSetting)
        self.buttonBoxOkCancel.accepted.connect(DialogNncSetting.accept)
        self.buttonBoxOkCancel.rejected.connect(DialogNncSetting.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNncSetting)

    def retranslateUi(self, DialogNncSetting):
        _translate = QtCore.QCoreApplication.translate
        DialogNncSetting.setWindowTitle(_translate("DialogNncSetting", "NNC Setting"))
        self.labelEnterHex.setText(_translate("DialogNncSetting", "Enter the NNC account number in HEX"))
        self.labelAcctFrom.setText(_translate("DialogNncSetting", "ACCT FROM"))
        self.labelAcctTo.setText(_translate("DialogNncSetting", "ACCT TO"))
        self.labelStep.setText(_translate("DialogNncSetting", "STEP"))


#程序入口，程序从此处启动PyQt设计的窗体
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    DialogNnc = QtWidgets.QDialog()
    ui = Ui_DialogNncSetting()
    ui.setupUi(DialogNnc)
    DialogNnc.show()
    sys.exit(app.exec_())